### ISSUE TITLE
MP4 m4a container

### ISSUE THREAD

**Issue by LeonarddeR** [savonet/ocaml-fdkaac#3]
Currently, liquidsoap is only able to output aac using fdkaac with the .aac file extension. Ocaml-fdkaac and liquidsoap should be able to save aac files in the m4a container, which adds support for metadata as well. There's a command line encoder for fdkaac (https://github.com/nu774/fdkaac) which is also able to save in the m4a container. To be exact, this command line encoder saves in .m4a whenever the raw aac transmux is selected, whereas ocaml-fdkaac doesn't.

**Comment by AlReem** [comment]
Dear toots,

Thanks for this valuable information.  However, I would like to use it in our radio station for providing playable files of previous programs for our audiences who missed hearing it live.  I use output.file for this with mp3 encoder.  I tried switching to aac plus for this an unfortunately, seeking stopped working.  

As requested in the question, do you know about any alternative to make fdkaac encode files in mp4 containers?
