### ISSUE TITLE
Re-enable dynamic linking

### ISSUE THREAD

**Issue by paddatrapper** [savonet/ocaml-fdkaac#5]
After the switch to dune (https://github.com/savonet/ocaml-fdkaac/commit/d3393ebecd8c851fd4a7796179888c7ab7069c0d), the loader stub (fdkaac_loader.cmxs) seems no longer to be built. Please re-add this feature, as it makes ocaml-fdkaac usable within Debian. Otherwise all OCaml things wanting to link against fdkaac would need to live in non-free.

Original bug report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=962220

**Comment by toots** [comment]
Hi @paddatrapper. I just committed changes that should bring back the dynamic loader. Any chance you could test it on your end?

**Comment by paddatrapper** [comment]
Thanks, sure I can give it a test

**Comment by paddatrapper** [comment]
@toots I tested patching v0.3.2 with that commit and get the following build error:

```
$ (cd _build/default/src && /usr/bin/ocamlopt.opt -shared fdkaac_dynlink.mli fdkaac_loader.ml -o fdkaac_loader.cmxs)
File "fdkaac_loader.ml", line 1:
Error: I/O error: fdkaac_loader.ml: No such file or directory
```

**Comment by toots** [comment]
@paddatrapper the file is part of the code. Did your patch include it?

**Comment by toots** [comment]
Sorry just getting back to this. This is definitely odd. Would a new release help to test from the actual code?

**Comment by paddatrapper** [comment]
I'll try build the current repo and see if that works

**Comment by paddatrapper** [comment]
It builds on HEAD and the loader is there, so it is probably something within the debian build. I'll bring it up to date with the git repo and publish that. Thanks for fixing!

**Comment by toots** [comment]
I'm removing the loader again sorry it's just too cumbersome to maintain. Please consider using our static build image (https://github.com/savonet/ffmpeg-static-build) or binary packages from the release page to enable fdkaac.

**Comment by toots** [comment]
Just to make it more clear: I am not fundamentally against it but I do not want to have to maintain it. We're in the process of switching all our modules to be included inside the liquidsoap code for optional compilation and the dynamic loader was removed to cut down on scope.

If there is an interested contributor who wants to be in charge of adding it back and keeping it working, I would be more than happy to help.

**Comment by paddatrapper** [comment]
I'll request it's removal from Debian and note that fdkaac support is no longer present in the liquidsoap package changelog. Thanks for all the support keeping this in Debian for so long
